--- 
- hosts: jboss
  become: yes
  vars:
#python -c 'import crypt; print crypt.crypt("ansible@2020","abcd1234455#$SALT")'
        password: abzrmVeDZnOpg
  tasks:
    - name: Criar uma lista de usuários
      user:
        name: "{{ item }}"
        state: present
        groups: wheel,root
        password: "{{ password  }}"
      loop:
        - ansible
        - luiz.eduardo

