---
- block:
    - name: Criando usuario de sistema
      user:
        name: "{{ wildfly_user }}"
        shell: /bin/false
        comment: "Wildfly User"
    
    - name: Baixando e instalando | Java e unzip
      yum:
        name: 
          - unzip
          - java-1.8.0-openjdk
        state: latest
      
    - name: Validando a instalacao do JAVA
      shell:
        cmd: rpm -q java-1.8.0-openjdk
      register: rpm_check
      failed_when: rpm_check.rc == 1

    - name: Checando firewalld
      shell:
        cmd: rpm -q firewalld
      register: rpm_check_firewall

    - name: Desativando firewalld
      systemd: 
        name: firewalld
        state: stopped
        enabled: false
      when:
        - rpm_check_firewall.rc == 0 

    - name: Verificando se wildfly-21.0.1.Final foi existe
      stat: 
        path: /wildfly-21.0.1.Final
      register: wildfly_check

    - name: Baixando wildfly 21.0.1
      unarchive:
        src: "{{ https_uri }}"
        dest: /
        remote_src: yes
      when: 
        - not wildfly_check.stat.exists

    - name: Criando link simbolico para /opt/wildfly
      file:
        src: /wildfly-21.0.1.Final  
        dest: /opt/wildfly
        state: link
    - file: 
        path: /opt/widfly
        owner: wildfly
        group: wildfly
        recurse: yes

    - name: Alterando proprietario do diretorio para wildfly
      file:
        path: /wildfly-21.0.1.Final
        owner: wildfly
        group: wildfly
        recurse: yes

    - name: Alterando endereco da interface em standalone.xml
      replace:
        path: /opt/wildfly/standalone/configuration/standalone.xml
        backup: yes
        regexp: '127\.0\.0\.1'
        replace: "{{ ansible_default_ipv4.address }}"
 
    - name: Criando usuario para acesso a console 
      shell:
        cmd: JBOSS_HOME='/opt/wildfly' /bin/bash -c '/opt/wildfly/bin/add-user.sh -u wildfly -p admin@wildfly'
      register: wildfly_user
    - debug:
        msg: "{{ wildfly_user }}"

    - name: Configurando inicializacao como servico
      copy:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        owner: wildfly
        mode: "0744"
        remote_src: yes
      with_items:
        - { src: /opt/wildfly/docs/contrib/scripts/init.d/wildfly-init-redhat.sh , dest: /etc/init.d/wildfly } 
        - { src: /opt/wildfly/docs/contrib/scripts/init.d/wildfly.conf , dest: /etc/default } 

    - name: Ajustando arquivo de servico
      replace:
        path: /etc/default/wildfly.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        backup: yes
      with_items:  
          - { regexp: '^# JBOSS_HOME\="\/opt\/wildfly"' , replace: 'JBOSS_HOME="/opt/wildfly"' }
          - { regexp: '^# JBOSS_USER\=wildfly' , replace: 'JBOSS_USER=wildfly' }
          - { regexp: '^# JBOSS_MODE\=standalone', replace: 'JBOSS_MODE=standalone' } 
          - { regexp: '^# JBOSS_CONFIG\=standalone.xml', replace: 'JBOSS_CONFIG=standalone.xml' }
          - { regexp: '^# STARTUP_WAIT\=60', replace: 'STARTUP_WAIT=60' } 
          - { regexp: '^# SHUTDOWN_WAIT\=60', replace: 'SHUTDOWN_WAIT=60' } 

    - name: Instalando wildfly como servico
      command: "{{ item }}"
      with_items:
        - /usr/sbin/chkconfig --add /etc/init.d/wildfly
        - /usr/sbin/chkconfig --level 2345 wildfly on
        - systemctl daemon-reload

    - name: Inicializando wildfly
      systemd: 
        name: wildfly
        state: started
        enabled: true
    
    - name: Checando porta 8080
      uri:
        url: http://{{ ansible_default_ipv4.address }}:8080
        return_content: true
      ignore_errors: yes
      register: status_8080
  
    - debug:
        msg: "{{ status_8080 }}"

  rescue: 
    - debug: 
        msg: "Ocorreu um erro durante a instalacao, debug o erro ou faca a instalacao manual\nLink para instacao manual: jboss-books.gitbooks.io/wildfly/content/instalacao/instalacao_passo_a_passo.html"


# tasks file for isweluiz.wildfly-install
...
